version: "3.8"
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  raw_events_collector:
    build:
      context: ./rec
    depends_on:
      - rabbit
    ports:
      - "8000:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  primary_raw_events_handler:
    build:
      context: ./preh
    depends_on:
      - rabbit
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  it_events_crawler:
    build:
      context: ./crawler/it_events_crawler
    depends_on:
      - rabbit
    ports:
      - "8080:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  softline_crawler:
    build:
      context: ./crawler/softline_crawler
    depends_on:
      - rabbit
    ports:
      - "8082:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  it_world_crawler:
    build:
      context: ./crawler/it_world_crawler
    depends_on:
      - rabbit
    ports:
      - "8008:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always

  mongodb_gui:
    image: mongo-express
    container_name: mongodb_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017

  event_das:
    build:
      context: ./das/event_das/
    depends_on:
      - rabbit
      - mongodb
    ports:
      - "8001:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://mongodb:27017"
