version: "3.8"
services:

  rabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"

  raw_events_collector:
    build:
      context: ./rec
    depends_on:
        - rabbit
    ports:
        - "8000:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  primary_raw_events_handler:
    build:
        context: ./preh
    depends_on:
        - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  it_events_crawler:
    build:
        context: ./crawler/it_events_crawler
    depends_on:
        - rabbit
    ports:
        - "8080:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"

  softline_crawler:
    build:
        context: ./crawler/softline_crawler
    depends_on:
        - rabbit
    ports:
        - "8081:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
