version: "3.8"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
  logger_db:
    image: mongo
    container_name: logger_db
    restart: always
  logger_gui:
    image: mongo-express
    container_name: logger_gui
    restart: always
    ports:
      - "8089:8081"
    depends_on:
      - logger_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=logger_db
      - ME_CONFIG_MONGODB_PORT=27017
  logger:
    image: maxkuznets0v/aggregator:logger
    depends_on:
      - rabbit
      - logger_db
    ports:
      - "8013:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://logger_db:27017"
  rec:
    image: maxkuznets0v/aggregator:raw_events_collector
    depends_on:
      - rabbit
      - logger
    ports:
      - "8001:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  preh:
    image: maxkuznets0v/aggregator:primary_raw_events_handler
    depends_on:
      - rabbit
    ports:
      - "8002:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  tag_das_db:
    image: mongo
    container_name: tag_das_db
    restart: always
  tag_das_gui:
    image: mongo-express
    container_name: tag_das_gui
    restart: always
    ports:
      - "8084:8081"
    depends_on:
      - tag_das_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=tag_das_db
      - ME_CONFIG_MONGODB_PORT=27017
  tag_das:
    image: maxkuznets0v/aggregator:tag_das
    depends_on:
      - rabbit
      - tag_das_db
    ports:
      - "8004:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://tag_das_db:27017"
  eta:
    image: maxkuznets0v/aggregator:event_theme_analyzer
    depends_on:
      - rabbit
    ports:
      - "8006:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  event_das_db:
    image: mongo
    container_name: event_das_db
    restart: always
  event_das_gui:
    image: mongo-express
    container_name: event_das_gui
    restart: always
    ports:
      - "8083:8081"
    depends_on:
      - event_das_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=event_das_db
      - ME_CONFIG_MONGODB_PORT=27017
  event_das:
    image: maxkuznets0v/aggregator:event_das
    depends_on:
      - rabbit
      - event_das_db
    ports:
      - "8003:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://event_das_db:27017"
  it_events_crawler:
    image: maxkuznets0v/aggregator:it_events_crawler
    depends_on:
      - rabbit
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  softline_crawler:
    image: maxkuznets0v/aggregator:softline_crawler
    depends_on:
      - rabbit
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  it_world_crawler:
    image: maxkuznets0v/aggregator:it_world_crawler
    depends_on:
      - rabbit
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  top_das_redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: top_das_redis
  top_das:
    image: maxkuznets0v/aggregator:top_das
    depends_on:
      - rabbit
    ports:
      - "8005:8000"
    environment:
      REDIS_HOST: "top_das_redis"
      REDIS_PORT: "6379"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  auth_redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: auth_redis
  auth:
    image: maxkuznets0v/aggregator:auth
    depends_on:
      - rabbit
    ports:
      - "8010:8000"
    environment:
      REDIS_HOST: "auth_redis"
      REDIS_PORT: "6379"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  filter:
    image: maxkuznets0v/aggregator:filter
    depends_on:
      - rabbit
    ports:
      - "8007:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  uis_db:
    image: mongo
    container_name: uis_db
    restart: always
  uis_gui:
    image: mongo-express
    container_name: uis_gui
    restart: always
    ports:
      - "8086:8081"
    depends_on:
      - uis_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=uis_db
      - ME_CONFIG_MONGODB_PORT=27017
  uis:
    image: maxkuznets0v/aggregator:uis
    depends_on:
      - rabbit
      - uis_db
    ports:
      - "8008:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://uis_db:27017"
  ranking:
    image: maxkuznets0v/aggregator:ranking_service
    depends_on:
      - rabbit
    ports:
      - "8009:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  gateway:
    image: maxkuznets0v/aggregator:gateway
    depends_on:
      - rabbit
    ports:
      - "8000:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
  likes_db:
    image: mongo
    container_name: likes_db
    restart: always
  likes_gui:
    image: mongo-express
    container_name: likes_gui
    restart: always
    ports:
      - "8087:8081"
    depends_on:
      - likes_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=likes_db
      - ME_CONFIG_MONGODB_PORT=27017
  likes:
    image: maxkuznets0v/aggregator:likes
    depends_on:
      - rabbit
      - likes_db
    ports:
      - "8011:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://likes_db:27017"
  favorites_db:
    image: mongo
    container_name: favorites_db
    restart: always
  favorites_gui:
    image: mongo-express
    container_name: favorites_gui
    restart: always
    ports:
      - "8088:8081"
    depends_on:
      - favorites_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=favorites_db
      - ME_CONFIG_MONGODB_PORT=27017
  favorites:
    image: maxkuznets0v/aggregator:favorites
    depends_on:
      - rabbit
      - favorites_db
    ports:
      - "8012:8000"
    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      MONGODB_CONNECTION_URL: "mongodb://favorites_db:27017"
