@host = localhost
@gateway_port = 8000

###
// Запрос событий для неавторизованного пользователя
GET http://{{host}}:{{gateway_port}}/feed HTTP/1.1

###
// Попробуем получить интересы неавторизованного пользователя
GET http://{{host}}:{{gateway_port}}/profile/interests HTTP/1.1