# Generated by Django 3.1.2 on 2020-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=30)),
                ('organizer', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('tags', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
