version: "3.8"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  event_theme_analyzer:
    build: ./../../eta/
    container_name: eta
    restart: always
    ports:
      - "8001:8000"

  tag_das:
    build: ../tag_das/
    container_name: tag_das
    restart: always
    depends_on: 
      - mongodb
    ports: 
      - "8002:8000"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  mongodb_gui:
    image: mongo-express
    container_name: mongodb_gui
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
